version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"             # наружу 5433, внутри всегда 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db          # сервисное имя
      DATABASE_PORT: "5432"      # внутри сети docker-compose
      DATABASE_NAME: mydb
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
    networks:
      - app-network
    # volumes:
    #   - ./logs:/build/logs    # если понадобится — расшарь путь в Docker Desktop (File Sharing)

networks:
  app-network:
    driver: bridge
    name: app-network

volumes:
  db_data:
