FROM golang:1.24 as builder
WORKDIR /app
COPY e2e/go.mod e2e/go.sum ./
RUN go mod download
COPY e2e/ ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /degradation ./cmd/degradation_many_chats_test

FROM alpine:3.20
RUN adduser -D -u 10001 appuser
USER appuser
WORKDIR /home/appuser
COPY --from=builder /degradation /usr/local/bin/degradation
ENTRYPOINT ["/usr/local/bin/degradation"]



