UNIT.TESTS=./service_logic (223), ./data_base (151)
INTEGRATION.TESTS=DepartmentSuite (16), ClientSuite (14)
E2E.TESTS=ChatSuite (13), AuthSuite (10), LessonSuite (6), PersonalDataSuite (4), APISuite (1)
Total.Tests=438
Date=2025-10-30 22:03:36
